# Generated by Django 5.0.6 on 2026-09-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved_lesson_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of lessons this user has written that were approved/published.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='True if the user has been reported recently. Forces all lessons to review.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_trusted_contributor',
            field=models.BooleanField(default=False, help_text='True after 3+ approved lessons. Trusted users get instant publishing.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rejected_lesson_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of lessons this user has written that were rejected.'),
        ),
    ]
