# Generated by Django 5.0.6 on 2026-09-30 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('language', 'Languages'), ('math', 'Math & School'), ('career', 'Life & Career'), ('practical', 'Practical & Home'), ('creative', 'Creative & Arts'), ('health', 'Health & Wellness'), ('civic', 'Civic & Community')], max_length=30)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('description', models.TextField(help_text='A short, friendly description of what this skill is.')),
                ('icon', models.CharField(default='📘', help_text='A single emoji representing this skill.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_self_taught', models.BooleanField(default=False, help_text='True if they learned by reading lessons alone.')),
                ('micro_proof', models.TextField(blank=True, help_text='A short description or link proving they can do this.')),
                ('learned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_links', to='skills.learninglink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_links', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='skills.skill')),
            ],
            options={
                'ordering': ['-learned_at'],
                'unique_together': {('user', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='StruggleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biggest_confusion', models.TextField(help_text='What confused you most while learning?')),
                ('breakthrough_moment', models.TextField(help_text='What finally made it click?')),
                ('advice_to_past_self', models.TextField(help_text='What would you tell yourself before starting?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='struggle', to='skills.learninglink')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Markdown or plain text. Keep it short and friendly.')),
                ('order', models.PositiveIntegerField(default=1)),
                ('estimated_minutes', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='skills.skill')),
            ],
            options={
                'ordering': ['skill', 'order'],
                'unique_together': {('skill', 'order')},
            },
        ),
    ]
