# Generated by Django 5.0.6 on 2026-09-30 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['skill', 'is_official', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Null for official StepUp lessons; set for community lessons.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='helpful_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quality_score',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='review_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('official', 'Official (StepUp Team)'), ('published', 'Community — Published'), ('pending', 'Community — Pending Review'), ('hidden', 'Community — Hidden (reported)'), ('rejected', 'Rejected')], default='official', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learninglink',
            name='is_self_taught',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='learninglink',
            name='micro_proof',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='📘', max_length=10),
        ),
        migrations.AlterField(
            model_name='strugglelog',
            name='advice_to_past_self',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='strugglelog',
            name='biggest_confusion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='strugglelog',
            name='breakthrough_moment',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='LessonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam / Promotion'), ('offensive', 'Offensive content'), ('wrong_skill', 'Wrong skill / off-topic'), ('copyright', 'Copyright violation'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='skills.lesson')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('lesson', 'reporter')},
            },
        ),
    ]
