# Generated by Django 5.0.6 on 2026-10-04 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_lesson_options_alter_lesson_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(help_text='When the session starts (UTC).')),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('status', models.CharField(choices=[('scheduled', 'Open Slot'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('jitsi_room', models.CharField(max_length=120, unique=True)),
                ('credits_paid', models.BooleanField(default=False, help_text="True once learner's credit has been transferred to teacher.")),
                ('credits_refunded', models.BooleanField(default=False)),
                ('learner_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('learner_feedback', models.TextField(blank=True)),
                ('teacher_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Optional session notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(blank=True, help_text='Null = open slot; set = booked session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_learned', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='skills.skill')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
